services:
  db:
    image: postgres
    restart: always
    container_name: postgres-flask-db
    ports: 
      - 5432:5432
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "flaskdb"